x-db-source: &db_source "postgresql://root:secret@postgres:5432/dummy_bank?sslmode=disable"

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dummy_bank
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dummy_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./db/migration:/migrations
    command: ["-path=/migrations", "-database", *db_source, "up"]
    depends_on:
      postgres:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: *db_source
      GIN_MODE: release
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: always
