// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dummybank/v1/service_dummy_bank.proto

package dummybankv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_dummybank_v1_service_dummy_bank_proto protoreflect.FileDescriptor

const file_dummybank_v1_service_dummy_bank_proto_rawDesc = "" +
	"\n" +
	"%dummybank/v1/service_dummy_bank.proto\x12\fdummybank.v1\x1a\"dummybank/v1/rpc_create_user.proto\x1a!dummybank/v1/rpc_login_user.proto\x1a\x1cgoogle/api/annotations.proto2\xe3\x01\n" +
	"\x10DummyBankService\x12e\n" +
	"\n" +
	"CreateUser\x12\x1f.dummybank.v1.CreateUserRequest\x1a .dummybank.v1.CreateUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12h\n" +
	"\tLoginUser\x12\x1e.dummybank.v1.LoginUserRequest\x1a\x1f.dummybank.v1.LoginUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/users/loginB:Z8github.com/jenkka/dummy-bank/pb/dummybank/v1;dummybankv1b\x06proto3"

var file_dummybank_v1_service_dummy_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: dummybank.v1.CreateUserRequest
	(*LoginUserRequest)(nil),   // 1: dummybank.v1.LoginUserRequest
	(*CreateUserResponse)(nil), // 2: dummybank.v1.CreateUserResponse
	(*LoginUserResponse)(nil),  // 3: dummybank.v1.LoginUserResponse
}
var file_dummybank_v1_service_dummy_bank_proto_depIdxs = []int32{
	0, // 0: dummybank.v1.DummyBankService.CreateUser:input_type -> dummybank.v1.CreateUserRequest
	1, // 1: dummybank.v1.DummyBankService.LoginUser:input_type -> dummybank.v1.LoginUserRequest
	2, // 2: dummybank.v1.DummyBankService.CreateUser:output_type -> dummybank.v1.CreateUserResponse
	3, // 3: dummybank.v1.DummyBankService.LoginUser:output_type -> dummybank.v1.LoginUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dummybank_v1_service_dummy_bank_proto_init() }
func file_dummybank_v1_service_dummy_bank_proto_init() {
	if File_dummybank_v1_service_dummy_bank_proto != nil {
		return
	}
	file_dummybank_v1_rpc_create_user_proto_init()
	file_dummybank_v1_rpc_login_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dummybank_v1_service_dummy_bank_proto_rawDesc), len(file_dummybank_v1_service_dummy_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummybank_v1_service_dummy_bank_proto_goTypes,
		DependencyIndexes: file_dummybank_v1_service_dummy_bank_proto_depIdxs,
	}.Build()
	File_dummybank_v1_service_dummy_bank_proto = out.File
	file_dummybank_v1_service_dummy_bank_proto_goTypes = nil
	file_dummybank_v1_service_dummy_bank_proto_depIdxs = nil
}
